package lt.vu.usecases.mybatis.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Courier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURIER.ID
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURIER.NAME
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURIER.SHOP_ID
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURIER.SPEED
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    private Integer speed;

    /**
     * ranka prirasytas
     */
    private Shop shop;
}