package lt.vu.usecases.mybatis.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.ID
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.NAME
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.PRICE
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    private Double price;
}