package lt.vu.usecases.mybatis.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class ShopItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOPITEM.SHOP_ID
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOPITEM.ITEM_ID
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    private Integer itemId;
}