package lt.vu.usecases.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOP.ID
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOP.NAME
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    private String name;

    /**
     * ranka prirasytas
     */
    private List<Item> items;
}