package lt.vu.usecases.mybatis.dao;

import java.util.List;
import lt.vu.usecases.mybatis.model.Courier;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CourierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURIER
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURIER
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    int insert(Courier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURIER
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    Courier selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURIER
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    List<Courier> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURIER
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    int updateByPrimaryKey(Courier record);
}