package lt.vu.usecases.mybatis.dao;

import java.util.List;
import lt.vu.usecases.mybatis.model.ShopItem;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ShopItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPITEM
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    int deleteByPrimaryKey(@Param("shopId") Integer shopId, @Param("itemId") Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPITEM
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    int insert(ShopItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPITEM
     *
     * @mbg.generated Mon Apr 22 19:48:17 EEST 2019
     */
    List<ShopItem> selectAll();
}